kind: "RoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1"
metadata:
  namespace: "{{ namespace }}"
  name: "{{ name }}"
  labels:
    kuberwave: "true"
subjects:
{%- for username in usernames %}
  - kind: {{subjectkind}}
    name: "{{ username }}"
{%- if subjectkind == UserKind::ServiceAccount %}
    namespace: default
    apiGroup: ""
{%- else %}
    apiGroup: rbac.authorization.k8s.io
{% endif -%}
{%- endfor -%}
roleRef:
  kind: "{{ bindingkind }}"
  name: "{{ rolename }}"
  apiGroup: ""
