apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ name }}"
secrets:
  - name: "{{ name }}-token"
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: "{{ name }}-token"
  annotations:
    kubernetes.io/service-account.name: "{{ name }}"