apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ name }}

{% if !binary_data.is_empty() %}
binaryData:
{% for field in binary_data %}
  {{ field.name }}: {{ field.value }}
{% endfor %}
{% endif %}

{% if !data.is_empty() %}
data:
{% for field in data %}
  {{ field.name }}: {{ field.value }}
{% endfor %}
{% endif %}