apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-within-namespace
  namespace: "{{ namespace }}"
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: "{{ namespace }}"
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cert-manager
  namespace: "{{ namespace }}"
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  ingress:
  - from: []
  policyTypes:
  - Ingress
{% for ingress in ingresses -%}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-http-{{ ingress.service }}
  namespace: "{{ namespace }}"
spec:
  podSelector:
    matchLabels:
      app: "{{ ingress.service }}"
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: "ingress"
    ports:
    - protocol: TCP
      port: {{ ingress.port }}
  policyTypes:
  - Ingress
{% endfor %}
